server:
  port: 8081
  servlet:
    context-path: /template

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/2huo
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: org/holen/template/dao/*.xml
  type-aliases-package: org.holen.template.domain.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql